# traefik.yml 
 
# set log level 
log: 
  level: DEBUG 
 
# enable the dashboard with useful information 
api: 
  dashboard: true 
  insecure: true 
 
# providers: in our case that's what we proxy. 
# at first we only need the Docker, 
# here's how to proxy external services  
providers: 
  docker: 
    # here's where you specify the network to add 
    # service to get it "picked up" by the traffic 
    network: traefik 
    # turn off "auto-scraping" of containers by traffic 
    # otherwise it will try to proxy all containers 
    exposedByDefault: false 
 
# entry points are basically just ports that will access 
# to Traefik and therefore to the services it proxies 
entrypoints: 
  # this is the name of the entry point for regular http traffic, usually called 
  # http or web, but you can put anything in here 
  http: 
    # the number of entry port 
    address: :80 
    http: 
      # set up a redirect for all requests to the https entry point 
      redirections: 
        entryPoint: 
          to: https 
          scheme: https 
          permanent: true 
  # create a https entry point on port 443, usually called 
  # https or websecure 
  https: 
    address: :443 
 
# ssl certificate resolvers: this is used to get certificates for domains. 
# We have just one for now and later we will add another, called Wildcard Resolver 
certificatesResolvers: 
  simple-resolver: 
    acme: 
      # acme challenge type, we need it so that letsencript can understand that this is our 
      # domain we need to specify the entry point on which the challenge will run 
      # more info about challenges here https://letsencrypt.org/docs/challenge-types/ 
      httpchallenge: 
        entrypoint: http 
      # letsencript needs your email, it will send all sorts of information there, 
      # e.g. your certificate's about to go bad 
      email: keith@webizly.com 
      # that's where Traefik will put the certificates, it's better to run volumetric 
      # that's what we'll do below 
      storage: /letsencrypt/acme.json 
 
accesslog: true 
